name: 2wr-app CI/CD

permissions:
      id-token: write

on:
  push:
    paths:
      - '2wr-app/**'
      - '.github/workflows/2wr-app.yaml'
    branches: [ main ]
  pull_request:
    paths:
      - '2wr-app/**'
      - '.github/workflows/2wr-app.yaml'
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ./2wr-app
    - run: npx playwright install chromium --with-deps
      working-directory: ./2wr-app
    - name: Write sample env file for e2e tests
      run: 'cp ./2wr-app/.env-sample ./2wr-app/.env'    
    - run: npm run e2etest
      env:
          TWO_WEEKS_READY_E2E_TEST_USERNAME: ${{ secrets.TWO_WEEKS_READY_E2E_TEST_USERNAME }}
          TWO_WEEKS_READY_E2E_TEST_PASSWORD: ${{ secrets.TWO_WEEKS_READY_E2E_TEST_PASSWORD }}
      working-directory: ./2wr-app
    - name: Upload e2e Test Results Recordings and Screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: e2e-test-results
        path: ./2wr-app/test-results
    - name: Upload e2e Test Results Report
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: e2e-test-report
        path: ./2wr-app/playwright-report

